app = "urbit-proxy"
primary_region = "syd"

[build]

[[services]]
  internal_port = 2222
  protocol = "tcp"

  [[services.ports]]
    port = 22

[env]
  GATEWAY_URL = "http://10.100.0.8:8080"

[mounts]
  source = "wg_keys"
  destination = "/data"

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
